config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
   resources :dog
   resources :fur
   resources :weather
   resources :character
   resources :issue
   resources :group
  root 'welcome#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/character.rb
class Character < ApplicationRecord
  validates :char_name, presence: true, length: { maximum: 50 }
end

app/models/dog.rb
class Dog < ApplicationRecord
  validates :breed_name, presence: true, length: { maximum: 50 }
  validates :size, presence: true, length: { maximum: 10 }
  validates :maint_cost, presence: true, length: { maximum: 10 }
end

app/models/fur.rb
class Fur < ApplicationRecord  
  validates :type_name, presence: true, length: { maximum: 20 }
end

app/models/group.rb
class Group < ApplicationRecord
  validates :group_name, presence: true, length: { maximum: 30 }
end

app/models/issue.rb
class Issue < ApplicationRecord
  validates :issue_name, presence: true, length: { maximum: 50 }
end

app/models/weather.rb
class Weather < ApplicationRecord
  validates :weather_name, presence: true, length: { maximum: 20 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/character_controller.rb
class CharacterController < ApplicationController
  def index
    @character = Character.all
  end

  def show
    @character = Character.find(params[:id])
  end

  def new
    @character = Character.new
  end

  def edit
    @character = Character.find(params[:id])
  end

  def create
    @character = Character.new(character_params)

    if @character.save
      redirect_to @character
    else
      render 'new'
    end
  end   

  def update
    @character = Character.find(params[:id])
  
    if @character.update(character_params)
      redirect_to @character
    else
      render 'edit'
    end
  end

  def destroy
    @character = Character.find(params[:id])
    @character.destroy

    redirect_to character_index_path
  end
   
  private
    def character_params
      params.require(:character).permit(:char_name)
    end
end

app/controllers/dog_controller.rb
class DogController < ApplicationController
  def index
    @dog = Dog.all
  end

  def show
    @dog = Dog.find(params[:id])
  end

  def new
    @dog = Dog.new
  end

  def edit
    @dog = Dog.find(params[:id])
  end

  def create
    @dog = Dog.new(dog_params)

    if @dog.save
      redirect_to @dog
    else
      render 'new'
    end
  end

  def update
    @dog = Dog.find(params[:id])
 
    if @dog.update(dog_params)
      redirect_to @dog
    else
      render 'edit'
    end
  end

  def destroy
    @dog = Dog.find(params[:id])
    @dog.destroy

    redirect_to dog_index_path
  end

  private
    def dog_params
      params.require(:dog).permit(:breed_name, :size, :maint_cost)
    end
end

app/controllers/fur_controller.rb
class FurController < ApplicationController
  def index
    @fur = Fur.all
  end

  def show
    @fur = Fur.find(params[:id])
  end

  def new
    @fur = Fur.new
  end

  def edit
    @fur = Fur.find(params[:id])
  end

  def create
    @fur = Fur.new(fur_params)

    if @fur.save
      redirect_to @fur
    else
      render 'new'
    end
  end   

  def update
    @fur = Fur.find(params[:id])
  
    if @fur.update(fur_params)
      redirect_to @fur
    else
      render 'edit'
    end
  end

  def destroy
    @fur = Fur.find(params[:id])
    @fur.destroy

    redirect_to fur_index_path
  end

  private
    def fur_params
      params.require(:fur).permit(:type_name)
    end
end

app/controllers/group_controller.rb
class GroupController < ApplicationController
  def index
    @group = Group.all
  end

  def show
    @group = Group.find(params[:id])
  end

  def new
    @group = Group.new
  end

  def edit
    @group = Group.find(params[:id])
  end

  def create
    @group = Group.new(group_params)

    if @group.save
      redirect_to @group
    else
      render 'new'
    end
  end   

  def update
    @group = Group.find(params[:id])
  
    if @group.update(group_params)
      redirect_to @group
    else
      render 'edit'
    end
  end

  def destroy
    @group = Group.find(params[:id])
    @group.destroy

    redirect_to group_index_path
  end
   
  private
    def group_params
      params.require(:group).permit(:group_name)
    end
end

app/controllers/issue_controller.rb
class IssueController < ApplicationController
  def index
    @issue = Issue.all
  end

  def show
    @issue = Issue.find(params[:id])
  end

  def new
    @issue = Issue.new
  end

  def edit
    @issue = Issue.find(params[:id])
  end

  def create
    @issue = Issue.new(issue_params)

    if @issue.save
      redirect_to @issue
    else
      render 'new'
    end
  end   

  def update
    @issue = Issue.find(params[:id])
  
    if @issue.update(issue_params)
      redirect_to @issue
    else
      render 'edit'
    end
  end

  def destroy
    @issue = Issue.find(params[:id])
    @issue.destroy

    redirect_to issue_index_path
  end

  private
    def issue_params
      params.require(:issue).permit(:issue_name)
    end
end

app/controllers/weather_controller.rb
class WeatherController < ApplicationController
  def index
    @weather = Weather.all
  end

  def show
    @weather = Weather.find(params[:id])
  end

  def new
    @weather = Weather.new
  end

  def edit
    @weather = Weather.find(params[:id])
  end
   
  def create
    @weather = Weather.new(weather_params)

    if @weather.save
      redirect_to @weather
    else
      render 'new'
    end
  end   

  def update
    @weather = Weather.find(params[:id])
  
    if @weather.update(weather_params)
      redirect_to @weather
    else
      render 'edit'
    end
  end

  def destroy
    @weather = Weather.find(params[:id])
    @weather.destroy

    redirect_to weather_index_path
  end

  private
    def weather_params
      params.require(:weather).permit(:weather_name)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/character_helper.rb
module CharacterHelper
end

app/helpers/dog_helper.rb
module DogHelper
end

app/helpers/fur_helper.rb
module FurHelper
end

app/helpers/group_helper.rb
module GroupHelper
end

app/helpers/issue_helper.rb
module IssueHelper
end

app/helpers/weather_helper.rb
module WeatherHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/character/edit.html.erb
<h1>Edit Character</h1>
 
<%= form_with(model: @character, local: true) do |form| %>
 
  <% if @character.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@character.errors.count, "error") %> prohibited
        this character entry from being saved:
      </h2>
      <ul>
        <% @character.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
 
  <p>
    <%= form.label :char_name %><br>
    <%= form.text_field :char_name %>
  </p>

  <p>
    <%= form.submit %>
  </p>
<% end %>
 
<%= link_to 'Back', character_index_path %>

app/views/character/index.html.erb
<h1>Listing Characters</h1>

<%= link_to 'New character', new_character_path %>
<%= link_to 'Home', welcome_index_path %>

<table>
  <tr>
    <th>Character name</th>
    <th></th>
  </tr>
 
  <% @character.each do |character| %>
    <tr>
      <td><%= character.char_name %></td>
      <td><%= link_to 'Show', character_path(character) %></td>
      <td><%= link_to 'Edit', edit_character_path(character) %></td>
      <td><%= link_to 'Destroy', character_path(character),
              method: :delete,
              data: { confirm: 'Are you sure?' } %></td>
  <% end %>
</table>

app/views/character/new.html.erb
<h1>Create character</h1>

<%= form_with scope: :character, url: character_index_path, local: true do |form| %>
  <p>
    <%= form.label :char_name %><br>
    <%= form.text_field :char_name %>
  </p>
 
  <p>
    <%= form.submit %>
  </p>
<% end %>

app/views/character/show.html.erb
<h1>Showing Character</h1>

<p>
  <strong>Character Name:</strong>
  <%= @character.char_name %>
</p>

<%= link_to 'Edit', edit_character_path(@character) %> | 
<%= link_to 'Back', character_index_path %>

app/views/dog/edit.html.erb
<h1>Edit Dog</h1>
 
<%= form_with(model: @dog, local: true) do |form| %>
 
  <% if @dog.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@dog.errors.count, "error") %> prohibited
        this dog entry from being saved:
      </h2>
      <ul>
        <% @dog.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
 
  <p>
    <%= form.label :breed_name %><br>
    <%= form.text_field :breed_name %>
  </p>
  
  <p>
    <%= form.label :size %><br>
    <%= form.text_field :size %>
  </p>

  <p>
    <%= form.label :maintenance_cost %><br>
    <%= form.text_field :maint_cost %>
  </p>

  <p>
    <%= form.submit %>
  </p>
<% end %>
 
<%= link_to 'Back', dog_index_path %>

app/views/dog/index.html.erb
<h1>Listing Dogs</h1>

<%= link_to 'New dog', new_dog_path %>
<%= link_to 'Home', welcome_index_path %>

<table>
  <tr>
    <th>Breed name</th>
    <th>Size</th>
    <th>Maintenance cost</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>
 
  <% @dog.each do |dog| %>
    <tr>
      <td><%= dog.breed_name %></td>
      <td><%= dog.size %></td>
      <td><%= dog.maint_cost %></td>
      <td><%= link_to 'Show', dog_path(dog) %></td>
      <td><%= link_to 'Edit', edit_dog_path(dog) %></td>
      <td><%= link_to 'Destroy', dog_path(dog),
              method: :delete,
              data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
</table>

app/views/dog/new.html.erb
<h1>Create Dog</h1>

<%= form_with scope: :dog, url: dog_index_path, local: true do |form| %>
  
  <% if @dog.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@dog.errors.count, "error") %> prohibited
        this dog entry from being saved:
      </h2>
      <ul>
        <% @dog.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= form.label :breed_name %><br>
    <%= form.text_field :breed_name %>
  </p>
 
  <p>
    <%= form.label :size %><br>
    <%= form.text_field :size %>
  </p>

  <p>
    <%= form.label :maint_cost %><br>
    <%= form.text_field :maint_cost %>
  </p>
 
  <p>
    <%= form.submit %>
  </p>
<% end %>

<%= link_to 'Back', dog_index_path %>

app/views/dog/show.html.erb
<h1>Showing Dog</h1>

<p>
  <strong>Breed name:</strong>
  <%= @dog.breed_name %>
</p>
 
<p>
  <strong>Size:</strong>
  <%= @dog.size %>
</p>

<p>
  <strong>Maintenance cost:</strong>
  <%= @dog.maint_cost %>
</p>

<%= link_to 'Edit', edit_dog_path(@dog) %> | 
<%= link_to 'Back', dog_index_path %>

app/views/fur/edit.html.erb
<h1>Edit Fur</h1>
 
<%= form_with(model: @fur, local: true) do |form| %>
 
  <% if @fur.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@fur.errors.count, "error") %> prohibited
        this fur entry from being saved:
      </h2>
      <ul>
        <% @fur.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
 
  <p>
    <%= form.label :type_name %><br>
    <%= form.text_field :type_name %>
  </p>

  <p>
    <%= form.submit %>
  </p>
<% end %>
 
<%= link_to 'Back', fur_index_path %>

app/views/fur/index.html.erb
<h1>Listing Furs</h1>

<%= link_to 'New fur', new_fur_path %>
<%= link_to 'Home', welcome_index_path %>

<table>
  <tr>
    <th>Type name</th>
    <th></th>
  </tr>
 
  <% @fur.each do |fur| %>
    <tr>
      <td><%= fur.type_name %></td>
      <td><%= link_to 'Show', fur_path(fur) %></td>
      <td><%= link_to 'Edit', edit_fur_path(fur) %></td>
      <td><%= link_to 'Destroy', fur_path(fur),
              method: :delete,
              data: { confirm: 'Are you sure?' } %></td>
  <% end %>
</table>

app/views/fur/new.html.erb
<h1>Create fur</h1>

<%= form_with scope: :fur, url: fur_index_path, local: true do |form| %>
  <p>
    <%= form.label :type_name %><br>
    <%= form.text_field :type_name %>
  </p>
 
  <p>
    <%= form.submit %>
  </p>
<% end %>

app/views/fur/show.html.erb
<h1>Showing Fur</h1>

<p>
  <strong>Type Name:</strong>
  <%= @fur.type_name %>
</p>

<%= link_to 'Edit', edit_fur_path(@fur) %> | 
<%= link_to 'Back', fur_index_path %>

app/views/group/edit.html.erb
<h1>Edit Group</h1>
 
<%= form_with(model: @group, local: true) do |form| %>
 
  <% if @group.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@group.errors.count, "error") %> prohibited
        this group entry from being saved:
      </h2>
      <ul>
        <% @group.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
 
  <p>
    <%= form.label :group_name %><br>
    <%= form.text_field :group_name %>
  </p>

  <p>
    <%= form.submit %>
  </p>
<% end %>
 
<%= link_to 'Back', group_index_path %>

app/views/group/index.html.erb
<h1>Listing Groups</h1>

<%= link_to 'New group', new_group_path %>
<%= link_to 'Home', welcome_index_path %>

<table>
  <tr>
    <th>Group name</th>
    <th></th>
  </tr>
 
  <% @group.each do |group| %>
    <tr>
      <td><%= group.group_name %></td>
      <td><%= link_to 'Show', group_path(group) %></td>
      <td><%= link_to 'Edit', edit_group_path(group) %></td>
      <td><%= link_to 'Destroy', group_path(group),
              method: :delete,
              data: { confirm: 'Are you sure?' } %></td>
  <% end %>
</table>

app/views/group/new.html.erb
<h1>Create group</h1>

<%= form_with scope: :group, url: group_index_path, local: true do |form| %>
  <p>
    <%= form.label :group_name %><br>
    <%= form.text_field :group_name %>
  </p>
 
  <p>
    <%= form.submit %>
  </p>
<% end %>

app/views/group/show.html.erb
<h1>Showing Group</h1>

<p>
  <strong>Group Name:</strong>
  <%= @group.group_name %>
</p>

<%= link_to 'Edit', edit_group_path(@group) %> | 
<%= link_to 'Back', group_index_path %>

app/views/issue/edit.html.erb
<h1>Edit Issue</h1>
 
<%= form_with(model: @issue, local: true) do |form| %>
 
  <% if @issue.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@issue.errors.count, "error") %> prohibited
        this issue entry from being saved:
      </h2>
      <ul>
        <% @issue.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
 
  <p>
    <%= form.label :issue_name %><br>
    <%= form.text_field :issue_name %>
  </p>

  <p>
    <%= form.submit %>
  </p>
<% end %>
 
<%= link_to 'Back', issue_index_path %>

app/views/issue/index.html.erb
<h1>Listing Issues</h1>

<%= link_to 'New issue', new_issue_path %>
<%= link_to 'Home', welcome_index_path %>

<table>
  <tr>
    <th>Issue name</th>
    <th></th>
  </tr>
 
  <% @issue.each do |issue| %>
    <tr>
      <td><%= issue.issue_name %></td>
      <td><%= link_to 'Show', issue_path(issue) %></td>
      <td><%= link_to 'Edit', edit_issue_path(issue) %></td>
      <td><%= link_to 'Destroy', issue_path(issue),
              method: :delete,
              data: { confirm: 'Are you sure?' } %></td>
  <% end %>
</table>

app/views/issue/new.html.erb
<h1>Create issue</h1>

<%= form_with scope: :issue, url: issue_index_path, local: true do |form| %>
  <p>
    <%= form.label :issue_name %><br>
    <%= form.text_field :issue_name %>
  </p>
 
  <p>
    <%= form.submit %>
  </p>
<% end %>

app/views/issue/show.html.erb
<h1>Showing Issue</h1>

<p>
  <strong>Issue Name:</strong>
  <%= @issue.issue_name %>
</p>

<%= link_to 'Edit', edit_issue_path(@issue) %> | 
<%= link_to 'Back', issue_index_path %>

app/views/weather/edit.html.erb
<h1>Edit Weather</h1>
 
<%= form_with(model: @weather, local: true) do |form| %>
 
  <% if @weather.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@weather.errors.count, "error") %> prohibited
        this weather entry from being saved:
      </h2>
      <ul>
        <% @weather.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
 
  <p>
    <%= form.label :weather_name %><br>
    <%= form.text_field :weather_name %>
  </p>

  <p>
    <%= form.submit %>
  </p>
<% end %>
 
<%= link_to 'Back', weather_index_path %>

app/views/weather/index.html.erb
<h1>Listing Weather</h1>

<%= link_to 'New weather', new_weather_path %>
<%= link_to 'Home', welcome_index_path %>

<table>
  <tr>
    <th>Weather name</th>
    <th></th>
  </tr>
 
  <% @weather.each do |weather| %>
    <tr>
      <td><%= weather.weather_name %></td>
      <td><%= link_to 'Show', weather_path(weather) %></td>
      <td><%= link_to 'Edit', edit_weather_path(weather) %></td>
      <td><%= link_to 'Destroy', weather_path(weather),
              method: :delete,
              data: { confirm: 'Are you sure?' } %></td>
  <% end %>
</table>

app/views/weather/new.html.erb
<h1>Create weather</h1>

<%= form_with scope: :weather, url: weather_index_path, local: true do |form| %>
  <p>
    <%= form.label :weather_name %><br>
    <%= form.text_field :weather_name %>
  </p>
 
  <p>
    <%= form.submit %>
  </p>
<% end %>

app/views/weather/show.html.erb
<h1>Showing Weather</h1>

<p>
  <strong>Weather Name:</strong>
  <%= @weather.weather_name %>
</p>

<%= link_to 'Edit', edit_weather_path(@weather) %> | 
<%= link_to 'Back', weather_index_path %>